### ISSUE TITLE
[Devepement branch] '***' is considered a bad breaker and once detected, clicking 'remove bad breakers' causes an exception.

### ISSUE THREAD

**Issue by Alephrin** [Gnurro/FinetuneReFormatter#8]
Branch: Current developement up until at least 6fdacb60128d8e8d62327435395c37c123119f51

If an input file contains *** as a chapter break, it's caught in the regex that checks for bad breakers. Once it's detected and added to the list, clicking the button to remove bad breakers throws an exception.

```Traceback (most recent call last):
  File "*REMOVED*\FinetuneReFormatter\baseGUI.py", line 966, in badDinkusReplace
    findMainWindow().curData = re.sub(f'\n{badDinkus}\n', '\n***\n', findMainWindow().curData)
  File "C:\Program Files\Python39\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Program Files\Python39\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files\Python39\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files\Python39\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files\Python39\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Program Files\Python39\lib\sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 2 (line 2, column 2)

**Comment by Gnurro** [comment]
`***` is the intended dinkus for NAI source data, so replacing it is unneccessary. In fact the error is thrown as the [Replace bad breakers] QuickFix replaces 'bad dinkusses' with `***` - it tries to replace `***` with `***` ad inifitum if `***` is in the found dinkusses.
[Find bad breakers] is intended to spot **any** diskusses, and the underlying regEx is intentionally broad. If the only thing showing up after hitting it is `***`, the data is fine already.

**Comment by Alephrin** [comment]
Ah, I wasn't sure if that was intentional or not. I guess the only actual issue is that it causes the exception then.
```foundDinkusses = list(filter(lambda a: a != '\n***\n', foundDinkusses))``` will evict it and prevent the exception but I don't know if that's the proper way to do it or how you'd prefer to handle it.

**Comment by Gnurro** [comment]
Added the filter line, thanks for that. `\n***\n` shouldn't show up in the 'bad breakers' anymore, and shouldn't result in that exception anymore, as well.
