### ISSUE TITLE
add __pycache__/ to gitignore

### ISSUE THREAD

**Issue by MNarath1** [Gnurro/FinetuneReFormatter#9]
__pycache__/ is a directory that gets generated on first time opening of baseGUI.py the files in the two directiories that get generated this way are user specific and should not be tracked by git.

**Comment by Gnurro** [comment]
You will have to set that up in your own git, as that directory does not exist in my local project and is not pushed by me.

**Comment by MNarath1** [comment]
> You will have to set that up in your own git, as that directory does not exist in my local project and is not pushed by me.

That directory seems to be generated on first runtime of baseGUI.py in two different locations inside trough i could fork this repro and set it up on my local repro then PR the change if you want.

**Comment by Gnurro** [comment]
It does not create this directory when I run it on my machine. This is something about your setup. Feel free to fork, though, and 'fix' this for yourself, if you can find out why it does this on your system.

**Comment by MNarath1** [comment]
curious i went trough those files that get generated inside those folders and while most of it is not readable there are actual comments from other files in it honestly no idea why it does that maybe its really my setup i use python 3.9.6 IDE trough beats me why it should be different

**Comment by MNarath1** [comment]
trough i am really at a loose why they get generated on my devices like i am installing the 3.9.6 Python and then run the py command to install requirements
